site_name: 2026 计算机网络实验文档

exclude_docs: |
  实验模板/

theme:
  name: material
  language: zh

nav:
  - 主页: index.md
  - Lab1: lab1.md
  - Lab2: lab2.md

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed

plugins:
  - search
  - glightbox

extra_css:
  - css/extra.css
